server:
  port: 80
  ip: 0.0.0.0

app:
  jwtTokens:
    accessToken:
      secret: "secret"
      expiration: 900000
    refreshToken:
      secret: "secret"
      expiration: 2592000000

spring:
  web:
    resources:
      static-locations: "file:static/"
  thymeleaf:
    prefix: "file:templates/"
  mvc:
    view:
      prefix: "file:templates/"
  datasource:
    url: "jdbc:mysql://localhost:3306/db"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            non_contextual_creation: true


  security:
    oauth2:
      client:
        registration:
          github:
            clientId: clientId
            clientSecret: clientSecret